query GetJobById ($id: String!) {
    # Query name corresponds to the action name on the server
    jobs_by_pk (id: $id) {
        position_name,
        url,
        location,
        description
    }
}