query JobSearch ($search: String!) {
    # Query name corresponds to the action name on the server
    job_search (args: { search: $search }) {
        id,
        location,
        position_name,
        description
    }
}